name: Building and deploying GitHub pages

on:
  schedule:
  # See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
  # run every day at 21:00 UTC
  - cron: "0 21 * * *"
  push:
 
jobs:
  daily_build:
    runs-on: ubuntu-latest
    env:
      COMMIT_AUTHOR: Daily Deploy Action
      COMMIT_AUTHOR_EMAIL: action@github.com
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install OPTiMaDe
      run: |
        python -m pip install --upgrade pip
        pip install -r make_ghpages/requirements.txt
    - name: make pages
      run: cd make_ghpages && python make_pages.py
    - name: commit to gh-pages
      run: ./make_ghpages/commit.sh
    - name: push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        branch: gh-pages
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
