name: Providers list validation

on:
  push:

jobs:
  validate:
    name: OPTiMaDe validator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install OPTiMaDe
      run: |
        python -m pip install --upgrade pip
        pip install optimade
        pip install pytest
    - name: Run validator on repository
      run: |
        py.test
