name: Validate all local index meta-dbs

on:
  workflow_dispatch:
    inputs:
      domain:
        description: Hostname to validate (production or a Netlify deploy preview)
        required: true
        default: providers.optimade.org
        type: string

env:
  DOMAIN: ${{ inputs.domain }}

jobs:
  validate:
    name: All local index meta-dbs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Wait a maximum of 3 min for the site to be up
      run: .github/workflows/wait_for_it.sh --host="${DOMAIN}" --port=443 -t 180
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install OPTIMADE
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools
        pip install optimade
    - name: Run validator for all local index meta-dbs
      run: |
        providers=$(find src/index-metadbs/ -maxdepth 1 -mindepth 1 -type d -printf '%f\n' | sort)
        for provider in ${providers}; do
          optimade-validator -vv --index "https://${DOMAIN}/index-metadbs/${provider}/v1/"
        done
