name: Scheduled validator

on: [push, pull_request]

jobs:

  pytest:
    name: Sanity checks (pytest)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install OPTIMADE
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools
        pip install optimade pytest
    - name: Run local tests on repository
      run: pytest

  validator:
    name: OPTIMADE validator
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      DEPLOY_PREVIEW: "deploy-preview-${{ github.event.number }}--optimade-providers.netlify.app"
    steps:
    - uses: actions/checkout@v2
    - name: Wait for the preview site to be up
      run: .github/workflows/wait_for_it.sh https://${DEPLOY_PREVIEW} -t 30
    - uses: Materials-Consortia/optimade-validator-action@v2
      with:
        index: yes
        protocol: https
        domain: ${DEPLOY_PREVIEW}
        path: /
        validator version: latest
        verbosity: 2

  validate_local_index_dbs:
    name: OPTIMADE validator (local index meta-dbs)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      DEPLOY_PREVIEW: "https://deploy-preview-${{ github.event.number }}--optimade-providers.netlify.app"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install OPTIMADE
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools
        pip install optimade
    - name: Run validator for all local index meta-dbs
      run: |
        providers=$(find src/index-metadbs/ -maxdepth 1 -mindepth 1 -type d -printf ' %f' | cut -d / -f 3 )
        .github/workflows/wait_for_it.sh ${DEPLOY_PREVIEW} -t 30
        for provider in ${providers[@]}; do
          optimade-validator -vv --index ${DEPLOY_PREVIEW}/index-metadbs/${provider}/v1/
        done
