name: Scheduled validator

on: [push, pull_request]

jobs:
  validate:
    name: OPTIMADE validator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install OPTIMADE
      run: |
        python -m pip install --upgrade pip
        pip install optimade
        pip install pytest
    - name: Run validator on repository
      run: |
        py.test
